# Generated by Django 5.2.13 on 2026-07-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/uploads/')),
                ('file_name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF')], max_length=20)),
                ('rows', models.IntegerField(default=0)),
                ('columns', models.IntegerField(default=0)),
                ('missing_values', models.IntegerField(default=0)),
                ('executive_summary', models.TextField(blank=True)),
                ('insights', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('conclusion', models.TextField(blank=True)),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='reports/pdf/')),
                ('docx_report', models.FileField(blank=True, null=True, upload_to='reports/docx/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
