from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT


class DOCXReportGenerator:

    def __init__(self, report_data, output_path):
        self.report = report_data
        self.output_path = output_path
        self.document = Document()

    # ----------------------------------------
    # Title
    # ----------------------------------------

    def add_title(self):

        heading = self.document.add_heading(
            self.report["title"],
            level=1
        )

        heading.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

        p = self.document.add_paragraph()

        p.add_run("Generated Date: ").bold = True

        p.add_run(
            self.report["generated_date"]
        )

    # ----------------------------------------
    # Executive Summary
    # ----------------------------------------

    def executive_summary(self):

        self.document.add_heading(
            "Executive Summary",
            level=2
        )

        self.document.add_paragraph(
            self.report["executive_summary"]
        )

    # ----------------------------------------
    # Dataset Information
    # ----------------------------------------

    def dataset_information(self):

        self.document.add_heading(
            "Dataset Overview",
            level=2
        )

        table = self.document.add_table(
            rows=1,
            cols=2
        )

        table.style = "Table Grid"

        header = table.rows[0].cells

        header[0].text = "Metric"
        header[1].text = "Value"

        for key, value in self.report[
            "dataset_information"
        ].items():

            row = table.add_row().cells

            row[0].text = str(key)
            row[1].text = str(value)

    # ----------------------------------------
    # KPI Table
    # ----------------------------------------

    def kpi_table(self):

        self.document.add_heading(
            "KPI Summary",
            level=2
        )

        kpis = self.report.get(
            "kpis",
            []
        )

        if len(kpis) == 0:

            self.document.add_paragraph(
                "No KPI information available."
            )

            return

        table = self.document.add_table(
            rows=1,
            cols=5
        )

        table.style = "Table Grid"

        hdr = table.rows[0].cells

        hdr[0].text = "Metric"
        hdr[1].text = "Total"
        hdr[2].text = "Average"
        hdr[3].text = "Maximum"
        hdr[4].text = "Minimum"

        for item in kpis:

            row = table.add_row().cells

            row[0].text = item["metric"]
            row[1].text = str(item["total"])
            row[2].text = str(item["average"])
            row[3].text = str(item["maximum"])
            row[4].text = str(item["minimum"])
                # ----------------------------------------
    # Bullet List Section
    # ----------------------------------------

    def add_bullet_section(self, heading, items):

        self.document.add_heading(
            heading,
            level=2
        )

        if not items:
            self.document.add_paragraph(
                "No information available."
            )
            return

        for item in items:
            self.document.add_paragraph(
                item,
                style="List Bullet"
            )

    # ----------------------------------------
    # Conclusion
    # ----------------------------------------

    def conclusion(self):

        self.document.add_heading(
            "Conclusion",
            level=2
        )

        self.document.add_paragraph(
            self.report.get(
                "conclusion",
                "Business report generated successfully."
            )
        )

    # ----------------------------------------
    # Footer
    # ----------------------------------------

    def footer(self):

        self.document.add_paragraph()

        footer = self.document.add_paragraph()

        footer.alignment = (
            WD_PARAGRAPH_ALIGNMENT.CENTER
        )

        run = footer.add_run(
            "Generated by AI Business Report Generator"
        )

        run.bold = True
        run.font.size = Pt(10)

        footer.add_run("\n")

        footer.add_run(
            self.report["generated_date"]
        ).font.size = Pt(9)

    # ----------------------------------------
    # Generate Word Report
    # ----------------------------------------

    def generate(self):

        self.add_title()

        self.executive_summary()

        self.dataset_information()

        self.kpi_table()

        self.add_bullet_section(
            "Business Insights",
            self.report.get(
                "insights",
                []
            )
        )

        self.add_bullet_section(
            "Potential Risks",
            self.report.get(
                "risks",
                []
            )
        )

        self.add_bullet_section(
            "Business Opportunities",
            self.report.get(
                "opportunities",
                []
            )
        )

        self.add_bullet_section(
            "Recommendations",
            self.report.get(
                "recommendations",
                []
            )
        )

        self.conclusion()

        self.footer()

        self.document.save(
            self.output_path
        )

        return self.output_path